### ISSUE TITLE
enigma2_box

### ISSUE THREAD

**Issue by mtester270** [technic/e2xvfb#1]
Hi,
im not sure if i do all as you write down in manual, but when i run an image in docker and after that run E2 a got stuck on network. Also can i ask for a contact email on you?

[Console] finished: route -n | grep tunl0
/bin/sh
[Network.py] interfaces - opening failed
nameservers: [[192, 168, 65, 5]]
read configured interface: {}
self.ifaces after loading: {'bonding_masters': {'preup': False, 'predown': False, 'ip': [0, 0, 0, 0], 'up': False, 'netmask': [0, 0, 0, 0], 'dhcp': True, 'gateway': [0, 0, 0, 0]}, 'tunl0': {'preup': False, 'predown': False, 'ip': [0, 0, 0, 0], 'up': False, 'netmask': [0, 0, 0, 0], 'dhcp': True, 'gateway': [0, 0, 0, 0]}, 'eth0': {'preup': False, 'predown': False, 'ip': [0, 0, 0, 0], 'up': False, 'netmask': [0, 0, 0, 0], 'dhcp': True, 'gateway': [0, 0, 0, 0]}}

**Comment by technic** [comment]
Did you connect with VNC, what do you see there?
Leave your email and I will contact you

**Comment by technic** [comment]
Here there is more detailed description https://github.com/technic/enigma2_example

**Comment by mtester270** [comment]
mtester270@gmail.com
